general {
    hide_cursor=True
}

background {
    monitor =
    path = ~/pictures/wp2.jpeg
    blur_passes = 1
    blur_size = 1 
    noise = 0.02
    contrast = 1.1
    brightness = 0.7
}
label {
    monitor =
    text = $TIME
    font_size = 50
    font_family = JetBrains Mono
    position = 650, 470
    halign = center
    valign = center
    color = rgb(0, 255, 220)
}

input-field {
    monitor =DP-1
    size = 340, 56
    position = 650, -470
    halign = center
    valign = center

    rounding = 1
    outline_thickness = 1 
    fade_on_empty = false

    inner_color = rgba(10, 10, 20, 0.6)
    outer_color = rgb(0, 255, 220)
    font_color = rgb(0, 255, 220)

    check_color = rgb(0, 255, 150)
    fail_color = rgb(255, 60, 60)

    placeholder_text = ENTER PASSWORD
}
label {
    monitor =
    text = >>> SYSTEM ONLINE — SECURE CONNECTION ESTABLISHED <<<
    font_family = JetBrains Mono
    font_size = 14
    position = 400,0
    halign = center
    valign = top
    color = rgba(0,255,220,0.25)
}

label {
    monitor =
    text = >>> SYSTEM ONLINE — SECURE CONNECTION ESTABLISHED <<<
    font_family = JetBrains Mono
    font_size = 14
    position = 0,0
    halign = center
    valign = top
    color = rgba(0,255,220,0.6)
}

label {
    monitor =
    text = >>> SYSTEM ONLINE — SECURE CONNECTION ESTABLISHED <<<
    font_family = JetBrains Mono
    font_size = 14
    position = -400,0
    halign = center
    valign = top
    color = rgba(0,255,220,0.25)
}

